In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])
dataset.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
x = dataset[["cgpa","profile_score"]].values[0].reshape(2,1)
y = dataset[["lpa"]].values[0][0]

# weights and bias initialize 

In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)         
    for l in range(1, L):
        parameters['w' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

In [5]:
initialize_parameters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
# 3. Forward Functions
def linear_forward(A_prev, w, b):
    return np.dot(w.T, A_prev) + b

In [7]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2
    for l in range(1, L+1):
        A_prev = A 
        Wl = parameters['w' + str(l)]
        bl = parameters['b' + str(l)]
        A = linear_forward(A_prev, Wl, bl)
    return A, A_prev

# update weights and bias 

In [8]:
# 4. Manual Update Function (Single Step)
def update_parameters_manual(parameters, y, y_hat, A1, x, lr=0.001):
    # Chain rule ke liye purane w2 ka backup lena zaroori hai
    w2_old = parameters['w2'].copy()
    
    # --- Layer 2 Updates ---
    parameters['w2'][0][0] += (lr * 2 * (y - y_hat) * A1[0][0])
    parameters['w2'][1][0] += (lr * 2 * (y - y_hat) * A1[1][0])
    parameters['b2'][0][0] += (lr * 2 * (y - y_hat))

    # --- Layer 1 Updates (Using w2_old) ---
    # Neuron 1 of Layer 1
    parameters['w1'][0][0] += (lr * 2 * (y - y_hat) * w2_old[0][0] * x[0][0])
    parameters['w1'][0][1] += (lr * 2 * (y - y_hat) * w2_old[0][0] * x[1][0])
    parameters['b1'][0][0] += (lr * 2 * (y - y_hat) * w2_old[0][0])

    # Neuron 2 of Layer 1
    parameters['w1'][1][0] += (lr * 2 * (y - y_hat) * w2_old[1][0] * x[0][0])
    parameters['w1'][1][1] += (lr * 2 * (y - y_hat) * w2_old[1][0] * x[1][0])
    parameters['b1'][1][0] += (lr * 2 * (y - y_hat) * w2_old[1][0])

    return parameters

In [9]:
# --- Single Execution Step ---
parameters = initialize_parameters([2,2,1])

In [10]:
# 1. Forward Pass
y_hat_matrix, A1 = L_layer_forward(x, parameters)
y_hat = y_hat_matrix[0][0]

In [11]:
print(f"Prediction (y_hat) before update: {y_hat}")
print(f"Original Weights (w2):\n{parameters['w2']}")

Prediction (y_hat) before update: 0.32000000000000006
Original Weights (w2):
[[0.1]
 [0.1]]


In [12]:
# 2. Update Step
parameters = update_parameters_manual(parameters, y, y_hat, A1, x)

print("\n--- Update Successful ---")
print(f"Updated Weights (w2):\n{parameters['w2']}")
print(f"Updated Weights (w1):\n{parameters['w1']}")


--- Update Successful ---
Updated Weights (w2):
[[0.111776]
 [0.111776]]
Updated Weights (w1):
[[0.105888 0.105888]
 [0.105888 0.105888]]


In [13]:
parameters

{'w1': array([[0.105888, 0.105888],
        [0.105888, 0.105888]]),
 'b1': array([[0.000736],
        [0.000736]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [14]:
x_row2 = dataset[["cgpa","profile_score"]].values[1].reshape(2,1)

y_row2 = dataset[["lpa"]].values[1][0] 

y_hat_matrix, A1 = L_layer_forward(x_row2, parameters)
y_hat = y_hat_matrix[0][0] # Prediction scalar hai

parameters = update_parameters_manual(parameters, y_row2, y_hat, A1, x_row2)

In [15]:
parameters

{'w1': array([[0.11310786, 0.11517068],
        [0.11310786, 0.11517068]]),
 'b1': array([[0.00176741],
        [0.00176741]]),
 'w2': array([[0.12741603],
        [0.12741603]]),
 'b2': array([[0.01658746]])}

In [16]:

x_row3 = dataset[["cgpa","profile_score"]].values[2].reshape(2,1)

y_row3 = dataset[["lpa"]].values[2][0] 

y_hat_matrix, A1 = L_layer_forward(x_row2, parameters)
y_hat = y_hat_matrix[0][0] # Prediction scalar hai

parameters = update_parameters_manual(parameters, y_row2, y_hat, A1, x_row2)

In [17]:
parameters

{'w1': array([[0.12116643, 0.1255317 ],
        [0.12116643, 0.1255317 ]]),
 'b1': array([[0.00291863],
        [0.00291863]]),
 'w2': array([[0.14378317],
        [0.14408137]]),
 'b2': array([[0.02562262]])}

In [18]:
x_row4 = dataset[["cgpa","profile_score"]].values[3].reshape(2,1)

y_row4 = dataset[["lpa"]].values[3][0] 

y_hat_matrix, A1 = L_layer_forward(x_row2, parameters)
y_hat = y_hat_matrix[0][0] # Prediction scalar hai

parameters = update_parameters_manual(parameters, y_row2, y_hat, A1, x_row2)

In [19]:
parameters

{'w1': array([[0.13003435, 0.13693331],
        [0.13005274, 0.13695695]]),
 'b1': array([[0.00418548],
        [0.00418811]]),
 'w2': array([[0.16089006],
        [0.16180365]]),
 'b2': array([[0.03443343]])}

# all in one program 

In [28]:
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
    Loss = []

    for j in range(dataset.shape[0]):
        # Data extraction
        X = dataset[['cgpa', 'profile_score']].values[j].reshape(2,1)
        y = dataset[['lpa']].values[j][0]

        # 1. Forward Pass
        y_hat_matrix, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat_matrix[0][0]

        # 2. Update Parameters
        parameters = update_parameters_manual(parameters, y, y_hat, A1, X)

        # Loss calculation
        Loss.append((y - y_hat)**2)

    print(f"\n{'='*10} Epoch {i+1} Summary {'='*10}")
    print(f"Average Loss: {np.array(Loss).mean():.4f}")
    
    print("\nLayer 1 (Hidden Layer):")
    print(f"Weights (w1):\n{parameters['w1']}")
    print(f"Bias (b1):\n{parameters['b1']}")
    
    print("\nLayer 2 (Output Layer):")
    print(f"Weights (w2):\n{parameters['w2']}")
    print(f"Bias (b2):\n{parameters['b2']}")
    print(f"{'='*35}\n")

print("Training Complete!")


========== Epoch 1 Summary ==========
Average Loss: 26.3741

Layer 1 (Hidden Layer):
Weights (w1):
[[0.13089303 0.15166842]
 [0.13091613 0.15172386]]
Bias (b1):
[[0.00504323]
 [0.00504785]]

Layer 2 (Output Layer):
Weights (w2):
[[0.17365565]
 [0.17567747]]
Bias (b2):
[[0.04030707]]


========== Epoch 2 Summary ==========
Average Loss: 20.0727

Layer 1 (Hidden Layer):
Weights (w1):
[[0.17481403 0.22420177]
 [0.17615052 0.22671404]]
Bias (b1):
[[0.0121643 ]
 [0.01239731]]

Layer 2 (Output Layer):
Weights (w2):
[[0.25913224]
 [0.27565777]]
Bias (b2):
[[0.07545486]]


========== Epoch 3 Summary ==========
Average Loss: 11.3001

Layer 1 (Hidden Layer):
Weights (w1):
[[0.22138204 0.30095347]
 [0.22656097 0.31011642]]
Bias (b1):
[[0.01970865]
 [0.02058119]]

Layer 2 (Output Layer):
Weights (w2):
[[0.3431363 ]
 [0.38330797]]
Bias (b2):
[[0.10167249]]


========== Epoch 4 Summary ==========
Average Loss: 4.1608

Layer 1 (Hidden Layer):
Weights (w1):
[[0.2545713  0.35795225]
 [0.26402869 0.374